FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install \
--no-cache-dir \
-r requirements.txt

COPY . .

CMD gunicorn \
--bind :8080 \
--workers 1 \
backend.app:app